---
title: "Part 1"
author: "lolo"
date: "2024-03-05"
output: html_document
---

```{r}
library(ggplot2)
library(MASS)
library(purrr)

# Define a function for the target distribution
l <- function(x) {
  0.5 * exp(-abs(x))
}

# Define the log of the target distribution
log_l <- function(x) {
  log(0.5) - abs(x)
}

# Initialize parameters
values_of_N <- 10000
values_of_s <- 1
x <- numeric(values_of_N + 1)

# Metropolis-Hastings algorithm
for (i in 2:(values_of_N + 1)) {
  x_proposed <- rnorm(1, mean = x[i - 1], sd = values_of_s)
  log_r <- log_l(x_proposed) - log_l(x[i - 1])
  u <- log(runif(1))
  if (u < log_r) {
    x[i] <- x_proposed
  } else {
    x[i] <- x[i - 1]
  }
}

# Generate more points for smoother curve
values_of_x <- seq(min(x), max(x), length.out = 1000)

# Plotting
ggplot() +
  geom_histogram(aes(x = x[-1], y = ..density..), bins = 50, color = 'black', fill = 'skyblue', alpha = 0.7) +
  geom_density(aes(x = x[-1]), color = 'blue', linewidth = 1) +
  geom_line(data = data.frame(x = values_of_x, y = l(values_of_x)), aes(x = x, y = l(x)), color = 'red') +
  labs(title = 'Histogram and Kernel Density Estimate vs. True Distribution in R',
       x = 'x',
       y = 'Density') +
  theme_minimal()

sample_mean_r <- mean(x[-1])
sample_std_r <- sd(x[-1])
print("Sample Mean in R:")
print(sample_mean_r)
print("Sample Standard Deviation in R:")
print(sample_std_r)


```


```{r}
# New parameters
values_of_N <- 2000
values_of_s <- seq(0.001, 1, length.out = 100)
values_of_J <- 4
x <- 0

l <- function(x) {
  0.5 * exp(-abs(x))
}

random_walk_metropolis <- function(x, N, s) {
  samples <- numeric(N)
  samples[1] <- x
  for (i in 2:N) {
    x_star <- rnorm(1, mean = samples[i-1], sd = s)
    r <- l(x_star) / l(samples[i-1])
    u <- runif(1)
    if (log(u) < log(r)) {
      samples[i] <- x_star
    } else {
      samples[i] <- samples[i-1]
    }
  }
  samples
}

calculate_r_hat <- function(N, J, s_values) {
  R_hat_values <- sapply(s_values, function(s) {
    M_j_values <- numeric(J)
    V_j_values <- numeric(J)
    for (j in 1:J) {
      x <- rnorm(1)
      samples <- random_walk_metropolis(x, N, s)
      M_j <- mean(samples)
      V_j <- var(samples)
      M_j_values[j] <- M_j
      V_j_values[j] <- V_j
    }
    W <- mean(V_j_values)
    M <- mean(M_j_values)
    B <- mean((M_j_values - M)^2) * N
    r_hat <- sqrt((B/W + 1) * (N-1)/N + (W/N))
    r_hat
  })
  R_hat_values
}

# Calculate R_hat for each scale value
R_hat_values <- calculate_r_hat(values_of_N, values_of_J, values_of_s)
R_hat_values

# Plotting
ggplot(data = data.frame(s = values_of_s, R_hat = R_hat_values), aes(x = values_of_s, y = R_hat)) +
  geom_line() +
  geom_hline(yintercept = 1.05, color = 'red', linetype = 'dashed') +
  labs(x = 's values', y = expression(hat(R)), title = expression(hat(R) ~ 'Values over Grid of s values in R')) +
  theme_minimal()
```

